apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: service-provider-integration-oauth
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: service-provider-integration-oauth
    app.kubernetes.io/part-of: alpo-studio
  name: service-provider-integration-oauth
  namespace: jduimovich
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: service-provider-integration-oauth
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: service-provider-integration-oauth
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:jduimovich-service-provider-integration-oauth-4cf41729e80f040fadfd1bf3f110a5989f58fa87
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
