apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: build-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: build-service
    app.kubernetes.io/part-of: alpo-studio
  name: build-service
  namespace: jduimovich
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: build-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: build-service
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:jduimovich-build-service-f13b881e3404ad3401fa7b533df3f7daddd11b55
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
